#!/usr/bin/env python

"""
Scans the overlay dir and writes found packages to project README.
"""

from __future__ import absolute_import, division, print_function, unicode_literals

import itertools
import os
import sys
import portage


def main():
    """script entry point"""
    here = os.path.normpath(os.path.join(os.path.abspath(__file__), os.pardir))
    readme = os.path.join(here, 'README.md')

    if not os.path.isfile(readme):
        print('Error: README.md is not found in {}'.format(here))
        return 1

    api = portage.db[portage.root]['porttree'].dbapi
    packages = api.cp_all(trees=(here,))

    with open(readme, 'r+') as file:
        contents = [line.strip() for line in file.readlines()]
        head = contents[0 : contents.index('## Packages') + 1]
        tail = contents[contents.index('## Repoman status') :]
        file.seek(0)
        file.write(
            os.linesep.join(
                itertools.chain(
                    head, ('``{}``'.format(pkg) for pkg in packages), [''], tail
                )
            )
        )
        file.write(os.linesep)
        file.truncate()
    return 0


if __name__ == '__main__':
    sys.exit(main())
