packages:
  - atom: app-admin/talosctl
    datasource: github-releases
    depName: siderolabs/talos
    version: 1.13.9

  - atom: app-admin/helmwave
    datasource: github-releases
    depName: helmwave/helmwave
    version: 0.42.1

  - atom: app-admin/topf
    datasource: github-releases
    depName: postfinance/topf
    version: 0.6.0

  - atom: net-vpn/netclient
    datasource: github-releases
    depName: gravitl/netclient
    version: 1.7.0
