name: Update Gentoo ebuilds

on:
  pull_request:
    paths:
      - '.github/.renovate/packages.yml'

permissions:
  contents: write

jobs:
  bump-ebuilds:
    runs-on: ubuntu-latest

    container:
      image: gentoo/stage3:latest

    steps:
      - name: Install dependencies
        run: |
          cat > /etc/portage/binrepos.conf/gentoo.conf <<EOF
          [gentoo]
          priority = 9999
          sync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64/
          verify-signature = true
          location = /var/cache/binhost/gentoo
          EOF
          printf 'FEATURES="getbinpkg binpkg-request-signature"\n' >> /etc/portage/make.conf

          emerge --sync --quiet
          emerge --oneshot --quiet --getbinpkg dev-vcs/git dev-util/pkgdev dev-python/pyyaml

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Checkout PR branch
        uses: actions/checkout@v7

      - name: Fetch PR base
        working-directory: ${{ github.workspace }}
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags origin "$BASE_SHA"

      - name: Update ebuilds
        working-directory: ${{ github.workspace }}
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git fetch
          .github/bin/bump-ebuild

      - name: Commit ebuild updates
        run: |
          pkgdev commit

      - name: Push changes
        run: |
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
