name: Update Gentoo ebuilds

on:
  pull_request:
    paths:
      - '.github/.renovate/packages.yml'

permissions:
  contents: write

jobs:
  bump-ebuilds:
    runs-on: ubuntu-latest

    container:
      image: gentoo/stage3:latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          emerge --sync --quiet
          emerge --oneshot --quiet dev-vcs/git dev-util/pkgdev dev-python/pyyaml

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Update ebuilds
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          .github/bin/bump-ebuild

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git add app-admin net-vpn

          if git diff --cached --quiet; then
            echo "No ebuild changes"
            exit 0
          fi

          git commit -m 'chore: update Gentoo ebuilds'
          git push
